name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 3166
          username: sabina
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /home/sabina/deploy.sh ${{ github.sha }}
