name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/sabina/catty-reminders-app
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u alvsbn --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d
            for i in {1..30}; do
              if curl -fsS http://127.0.0.1:8181/login > /dev/null; then
                echo "App is ready"
                break
               fi
               echo "Waiting..."
               sleep 5
             done
